[BUG] Sort m2m fields before comparing them with `diff(...)`
tortoise/aerich pull request #271
Opened 2022-10-13 16:57 UTC by mykolasolodukha

### What?
- [x] Sort `new_m2m_fields` before comparing them using `dictdiffer.diff(...)`.

### Why?
Otherwise, if one adds more m2m fields, the `diff` would produce the `action="change"` result, instead of the `action="add"` one. See:
- https://github.com/inveniosoftware/dictdiffer/issues/100
- https://github.com/inveniosoftware/dictdiffer/issues/170

### How to test?
Try migrating this:
```python
# models.py
class User(tortoise.Model):

    id = fields.BigIntField(pk=True, generated=False)

    first_name = fields.TextField(null=True)
    last_name = fields.TextField(null=True)

    groups: fields.ManyToManyRelation[Group]

class Group(tortoise.Model):

    name = fields.TextField()

    users: fields.ManyToManyRelation[User] = fields.ManyToManyField(
        "bot.User", through="group__user", related_name="groups"
    )
```
To this:
```python
# models.py
class User(tortoise.Model):

    id = fields.BigIntField(pk=True, generated=False)

    first_name = fields.TextField(null=True)
    last_name = fields.TextField(null=True)

    groups: fields.ManyToManyRelation[Group]
    admin_in_groups: fields.ManyToManyRelation[Group]

class Group(tortoise.Model):

    name = fields.TextField()

    users: fields.ManyToManyRelation[User] = fields.ManyToManyField(
        "bot.User", through="group__user", related_name="groups"
    )
    admins: fields.ManyToManyRelation[User] = fields.ManyToManyField(
        "bot.User", through="group__admin", related_name="admin_in_groups"
    )
```

```sh
aerich migrate --name "add_group_admins"
```

### Anything else?
- I think this kind of sorting might help with other types of fields as well, but I have no time to investigate that right now. This fix is urgent for me, though.

2022-10-25 03:13 UTC, LanceMoe commented
I have the same problem, aerich doesn't work at all. This PR solves the problem. Please merge this!

2024-12-04 15:56 UTC, waketzheng requested changes
It is better to only sort new m2m fields when it has more than one elements:
```py
if len(new_m2m_fields) > 1 and old_m2m_fields:
    length = len(old_m2m_fields)
    field_index = {f['name']: i for i, f in enumerate(new_m2m_fields)}
    new_m2m_fields.sort(key=lambda field: field_index.get(field['name'], length))
```

2024-12-05 08:05 UTC, waketzheng approved these changes

2024-12-05 09:06 UTC, waketzheng commented
This PR will fixes #150

2024-12-05 09:41 UTC, merged